// =============================================
// KNOX SHOP - LANG.JS
// Đa ngôn ngữ: Tiếng Việt & Tiếng Anh
// =============================================

const LANG = {
  vi: {
    // Navigation
    'nav.home': '🏠 Trang chủ',
    'nav.services': '🎮 Dịch vụ',
    'nav.history': '📜 Lịch sử',
    'nav.tickets': '🎫 Hỗ trợ',
    'nav.dashboard': '📊 Dashboard',
    
    // Common
    'common.login': 'Đăng nhập',
    'common.register': 'Đăng ký',
    'common.logout': 'Đăng xuất',
    'common.buy_now': '🛒 Mua ngay',
    'common.contact': '📞 Liên hệ',
    'common.price': 'Giá',
    'common.status': 'Trạng thái',
    'common.pending': 'Chờ duyệt',
    'common.completed': 'Hoàn thành',
    'common.cancelled': 'Đã hủy',
    'common.copy': '📋 Sao chép',
    'common.copied': '✅ Đã sao chép!',
    'common.close': 'Đóng',
    'common.confirm': 'Xác nhận',
    'common.cancel': 'Hủy',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.save': 'Lưu',
    'common.search': 'Tìm kiếm...',
    'common.no_data': 'Không có dữ liệu',
    'common.loading': 'Đang tải...',
    'common.error': 'Lỗi',
    'common.success': 'Thành công',
    'common.warning': 'Cảnh báo',
    'common.info': 'Thông tin',
    
    // Auth
    'auth.welcome': 'Chào mừng đến với KNOX Shop',
    'auth.username': 'Tên đăng nhập',
    'auth.password': 'Mật khẩu',
    'auth.confirm_password': 'Xác nhận mật khẩu',
    'auth.email': 'Email',
    'auth.referral_code': 'Mã giới thiệu',
    'auth.login_btn': 'Đăng nhập',
    'auth.register_btn': 'Đăng ký',
    'auth.forgot_password': 'Quên mật khẩu?',
    'auth.no_account': 'Chưa có tài khoản?',
    'auth.have_account': 'Đã có tài khoản?',
    'auth.username_required': 'Tên đăng nhập phải >= 3 ký tự',
    'auth.password_required': 'Mật khẩu phải >= 6 ký tự',
    'auth.admin_only': 'Không được đăng ký tên admin',
    'auth.login_success': 'Đăng nhập thành công!',
    'auth.register_success': 'Đăng ký thành công!',
    'auth.login_failed': 'Đăng nhập thất bại',
    'auth.user_not_found': 'Tên không tồn tại',
    'auth.wrong_password': 'Mật khẩu sai',
    'auth.account_locked': 'Tài khoản bị khóa! Liên hệ admin.',
    'auth.admin_wrong_password': 'Mật khẩu Admin sai',
    
    // User
    'user.balance': 'Số dư',
    'user.vip': 'VIP',
    'user.total_deposited': 'Tổng nạp',
    'user.total_spent': 'Tổng chi',
    'user.total_orders': 'Tổng đơn',
    'user.completed_orders': 'Đơn hoàn thành',
    'user.referral': 'Mã giới thiệu',
    'user.referred_count': 'Số người giới thiệu',
    'user.vip_levels': {
      'NEW': 'NEW',
      'VIP1': 'VIP 1',
      'VIP2': 'VIP 2',
      'VIP3': 'VIP 3',
      'VIP4': 'VIP 4'
    },
    'user.vip_discount': 'Ưu đãi giảm',
    'user.next_vip': 'VIP tiếp theo',
    'user.need_more': 'Cần thêm',
    'user.current_discount': 'Giảm giá hiện tại',
    
    // Deposit
    'deposit.title': '💳 Nạp tiền',
    'deposit.amount': 'Số tiền',
    'deposit.method': 'Phương thức',
    'deposit.note': 'Ghi chú',
    'deposit.bank': 'Ngân hàng',
    'deposit.card': 'Thẻ cào',
    'deposit.quick_amounts': '10K, 20K, 50K, 100K, 200K, 500K',
    'deposit.min_amount': 'Số tiền tối thiểu 10.000đ',
    'deposit.vcb': 'Vietcombank',
    'deposit.gcoin': 'GCoin',
    'deposit.stk': 'STK: 1064291846',
    'deposit.owner': 'NGUYEN TRUNG NGUYEN',
    'deposit.content': 'Nội dung chuyển khoản',
    'deposit.instruction': 'Sau khi chuyển, admin sẽ duyệt và cộng tiền tự động.',
    'deposit.success': 'Đã tạo lệnh nạp, vui lòng chuyển khoản!',
    'deposit.code_generated': 'Mã nạp đã tạo',
    
    // Card deposit
    'card.title': '💳 Nạp thẻ cào',
    'card.telco': 'Nhà mạng',
    'card.amount': 'Mệnh giá',
    'card.serial': 'Số seri',
    'card.code': 'Mã thẻ',
    'card.discount': 'Chiết khấu',
    'card.receive': 'Số tiền nhận được',
    'card.viettel': 'Viettel',
    'card.mobi': 'MobiFone',
    'card.vina': 'VinaPhone',
    'card.vietnamobile': 'Vietnamobile',
    
    // Order
    'order.title': '📦 Đơn hàng',
    'order.code': 'Mã đơn',
    'order.service': 'Dịch vụ',
    'order.game_account': 'Tài khoản game',
    'order.game_password': 'Mật khẩu game',
    'order.note': 'Ghi chú',
    'order.voucher': 'Mã giảm giá',
    'order.apply_voucher': 'Áp dụng',
    'order.price': 'Giá',
    'order.status': 'Trạng thái',
    'order.progress': 'Tiến độ',
    'order.download': 'Link tải',
    'order.rating': 'Đánh giá',
    'order.reject_reason': 'Lý do từ chối',
    'order.cancel': 'Hủy đơn',
    'order.rate': 'Đánh giá',
    'order.rating_placeholder': 'Đánh giá 1-5 sao',
    'order.comment_placeholder': 'Nhận xét của bạn',
    'order.cancel_confirm': 'Bạn chắc chắn muốn hủy đơn này?',
    'order.cancel_success': 'Đã hủy đơn! Tiền đã hoàn về ví.',
    'order.create_success': 'Đặt hàng thành công!',
    'order.not_enough_balance': 'Không đủ tiền! Đang mở modal nạp tiền...',
    'order.game_account_required': 'Tài khoản game phải >=3 ký tự',
    'order.game_password_required': 'Mật khẩu game phải >=3 ký tự',
    
    // Ticket
    'ticket.title': '🎫 Hỗ trợ',
    'ticket.new': '➕ Tạo ticket mới',
    'ticket.code': 'Mã ticket',
    'ticket.subject': 'Tiêu đề',
    'ticket.message': 'Nội dung',
    'ticket.reply': 'Admin trả lời',
    'ticket.status': 'Trạng thái',
    'ticket.open': 'Đang mở',
    'ticket.answered': 'Đã trả lời',
    'ticket.closed': 'Đã đóng',
    'ticket.create_success': 'Ticket đã tạo!',
    'ticket.subject_required': 'Vui lòng nhập tiêu đề',
    'ticket.message_required': 'Vui lòng nhập nội dung',
    
    // Notification
    'notif.title': '📢 Thông báo',
    'notif.no_data': 'Không có thông báo mới',
    'notif.new_order': 'Đơn hàng mới',
    'notif.order_updated': 'Đơn hàng cập nhật',
    'notif.order_cancelled': 'Đơn hàng bị hủy',
    'notif.deposit_success': 'Nạp tiền thành công',
    'notif.deposit_failed': 'Nạp tiền thất bại',
    'notif.account_locked': 'Tài khoản bị khóa',
    'notif.account_unlocked': 'Tài khoản được mở khóa',
    'notif.password_reset': 'Mật khẩu đã được reset',
    'notif.broadcast': 'Thông báo từ admin',
    
    // Admin
    'admin.title': '👑 KNOX Admin',
    'admin.dashboard': '📊 Dashboard',
    'admin.orders': '📦 Đơn hàng',
    'admin.deposits': '💳 Nạp tiền',
    'admin.cards': '💳 Thẻ cào',
    'admin.tickets': '🎫 Ticket',
    'admin.users': '👥 Users',
    'admin.scripts': '📜 Scripts',
    'admin.deals': '🔥 Hot Deals',
    'admin.vouchers': '🎫 Vouchers',
    'admin.reviews': '⭐ Reviews',
    'admin.broadcast': '📢 Broadcast',
    'admin.logs': '📋 Logs',
    'admin.backup': '💾 Backup',
    'admin.logout': 'Đăng xuất',
    'admin.stat_orders': 'Tổng đơn',
    'admin.stat_pending_orders': 'Đơn chờ',
    'admin.stat_completed_orders': 'Hoàn thành',
    'admin.stat_pending_deposits': 'Nạp chờ',
    'admin.stat_pending_cards': 'Thẻ chờ',
    'admin.stat_open_tickets': 'Ticket mở',
    'admin.stat_users': 'Tổng user',
    'admin.stat_revenue': 'Doanh thu',
    'admin.approve': 'Duyệt',
    'admin.reject': 'Từ chối',
    'admin.reject_reason': 'Lý do từ chối',
    'admin.reject_required': 'Vui lòng nhập lý do từ chối',
    'admin.backup_success': 'Backup thành công!',
    'admin.broadcast_sent': 'Broadcast đã gửi đến tất cả user!',
    
    // Products
    'products.mod_skill': 'Mod Skill',
    'products.mod_fish': 'Mod Cá',
    'products.mod_level': 'Mod Level',
    'products.mod_item': 'Mod Item',
    'products.mod_pet': 'Mod Pet',
    'products.mod_diamond': 'Mod Kim Cương',
    'products.mod_dieuhon': 'Mod Điếu Hồn',
    'products.mod_full': 'Câu Cá Vạn Cân Full',
    'products.sniper_arena': 'Sniper Arena',
    'products.ban_mod': 'Bản Mod (Tự Mod)',
    'products.cau_chung': 'Câu Chung (Theo Giờ)',
    
    // Hot Deals
    'hot_deals.title': '🔥 HOT DEALS',
    'hot_deals.no_data': 'Hiện chưa có hot deal',
    'hot_deals.discount': 'Giảm',
    
    // Dashboard
    'dashboard.title': '📊 Dashboard cá nhân',
    'dashboard.balance': 'Số dư',
    'dashboard.total_deposited': 'Tổng nạp',
    'dashboard.total_spent': 'Tổng chi',
    'dashboard.total_orders': 'Đơn hàng',
    'dashboard.completed_orders': 'Hoàn thành',
    'dashboard.vip_level': 'VIP',
    'dashboard.next_vip': 'VIP tiếp theo',
    'dashboard.need_more': 'Cần thêm',
    'dashboard.current_discount': 'Giảm giá hiện tại',
    'dashboard.reached_max': 'Đã đạt VIP4',
    
    // Top Deposit
    'top_deposit.title': '🏆 Top nạp tháng',
    'top_deposit.no_data': 'Chưa có dữ liệu nạp tháng',
    
    // Referral
    'referral.title': '👥 Giới thiệu bạn bè',
    'referral.code': 'Mã giới thiệu',
    'referral.reward': 'Thưởng giới thiệu: +10.000đ/người',
    'referral.count': 'Số người đã giới thiệu',
    
    // Voucher
    'voucher.title': '🎫 Mã giảm giá',
    'voucher.code': 'Mã code',
    'voucher.discount': 'Giảm',
    'voucher.used': 'Đã dùng',
    'voucher.max_uses': 'Tổng lượt',
    'voucher.apply_success': 'Áp dụng thành công!',
    'voucher.invalid': 'Mã không hợp lệ',
    'voucher.expired': 'Mã đã hết lượt',
    
    // Review
    'review.title': '⭐ Đánh giá sản phẩm',
    'review.rating': 'Sao',
    'review.comment': 'Nhận xét',
    'review.thank_you': 'Cảm ơn bạn đã đánh giá!',
    
    // Time
    'time.today': 'Hôm nay',
    'time.this_week': 'Tuần này',
    'time.this_month': 'Tháng này',
    'time.this_year': 'Năm nay',
    
    // PWA
    'pwa.install': '📲 Cài đặt ứng dụng',
    'pwa.install_desc': 'Cài KNOX Shop vào màn hình chính để trải nghiệm tốt hơn!',
    'pwa.install_btn': 'Cài đặt',
    'pwa.install_later': 'Để sau',
    
    // Chat
    'chat.title': '📞 Liên hệ',
    'chat.zalo': '💬 Zalo',
    'chat.telegram': '✈️ Telegram'
  },
  
  en: {
    // Navigation
    'nav.home': '🏠 Home',
    'nav.services': '🎮 Services',
    'nav.history': '📜 History',
    'nav.tickets': '🎫 Support',
    'nav.dashboard': '📊 Dashboard',
    
    // Common
    'common.login': 'Login',
    'common.register': 'Register',
    'common.logout': 'Logout',
    'common.buy_now': '🛒 Buy Now',
    'common.contact': '📞 Contact',
    'common.price': 'Price',
    'common.status': 'Status',
    'common.pending': 'Pending',
    'common.completed': 'Completed',
    'common.cancelled': 'Cancelled',
    'common.copy': '📋 Copy',
    'common.copied': '✅ Copied!',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.save': 'Save',
    'common.search': 'Search...',
    'common.no_data': 'No data',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    
    // Auth
    'auth.welcome': 'Welcome to KNOX Shop',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm password',
    'auth.email': 'Email',
    'auth.referral_code': 'Referral code',
    'auth.login_btn': 'Login',
    'auth.register_btn': 'Register',
    'auth.forgot_password': 'Forgot password?',
    'auth.no_account': "Don't have an account?",
    'auth.have_account': 'Already have an account?',
    'auth.username_required': 'Username must be >= 3 characters',
    'auth.password_required': 'Password must be >= 6 characters',
    'auth.admin_only': 'Cannot register with admin username',
    'auth.login_success': 'Login successful!',
    'auth.register_success': 'Registration successful!',
    'auth.login_failed': 'Login failed',
    'auth.user_not_found': 'Username not found',
    'auth.wrong_password': 'Wrong password',
    'auth.account_locked': 'Account locked! Contact admin.',
    'auth.admin_wrong_password': 'Admin password wrong',
    
    // User
    'user.balance': 'Balance',
    'user.vip': 'VIP',
    'user.total_deposited': 'Total deposited',
    'user.total_spent': 'Total spent',
    'user.total_orders': 'Total orders',
    'user.completed_orders': 'Completed orders',
    'user.referral': 'Referral code',
    'user.referred_count': 'Referred count',
    'user.vip_levels': {
      'NEW': 'NEW',
      'VIP1': 'VIP 1',
      'VIP2': 'VIP 2',
      'VIP3': 'VIP 3',
      'VIP4': 'VIP 4'
    },
    'user.vip_discount': 'Discount',
    'user.next_vip': 'Next VIP',
    'user.need_more': 'Need more',
    'user.current_discount': 'Current discount',
    
    // Deposit
    'deposit.title': '💳 Deposit',
    'deposit.amount': 'Amount',
    'deposit.method': 'Method',
    'deposit.note': 'Note',
    'deposit.bank': 'Bank',
    'deposit.card': 'Card',
    'deposit.quick_amounts': '10K, 20K, 50K, 100K, 200K, 500K',
    'deposit.min_amount': 'Minimum amount is 10.000đ',
    'deposit.vcb': 'Vietcombank',
    'deposit.gcoin': 'GCoin',
    'deposit.stk': 'Account: 1064291846',
    'deposit.owner': 'NGUYEN TRUNG NGUYEN',
    'deposit.content': 'Transfer content',
    'deposit.instruction': 'After transfer, admin will approve and add balance automatically.',
    'deposit.success': 'Deposit request created! Please transfer.',
    'deposit.code_generated': 'Deposit code generated',
    
    // Card deposit
    'card.title': '💳 Card deposit',
    'card.telco': 'Telecom',
    'card.amount': 'Amount',
    'card.serial': 'Serial',
    'card.code': 'Card code',
    'card.discount': 'Discount',
    'card.receive': 'Receive amount',
    'card.viettel': 'Viettel',
    'card.mobi': 'MobiFone',
    'card.vina': 'VinaPhone',
    'card.vietnamobile': 'Vietnamobile',
    
    // Order
    'order.title': '📦 Orders',
    'order.code': 'Order code',
    'order.service': 'Service',
    'order.game_account': 'Game account',
    'order.game_password': 'Game password',
    'order.note': 'Note',
    'order.voucher': 'Voucher code',
    'order.apply_voucher': 'Apply',
    'order.price': 'Price',
    'order.status': 'Status',
    'order.progress': 'Progress',
    'order.download': 'Download link',
    'order.rating': 'Rating',
    'order.reject_reason': 'Reject reason',
    'order.cancel': 'Cancel order',
    'order.rate': 'Rate',
    'order.rating_placeholder': 'Rate 1-5 stars',
    'order.comment_placeholder': 'Your comment',
    'order.cancel_confirm': 'Are you sure you want to cancel this order?',
    'order.cancel_success': 'Order cancelled! Balance refunded.',
    'order.create_success': 'Order created successfully!',
    'order.not_enough_balance': 'Insufficient balance! Opening deposit modal...',
    'order.game_account_required': 'Game account must be >=3 characters',
    'order.game_password_required': 'Game password must be >=3 characters',
    
    // Ticket
    'ticket.title': '🎫 Support',
    'ticket.new': '➕ New ticket',
    'ticket.code': 'Ticket code',
    'ticket.subject': 'Subject',
    'ticket.message': 'Message',
    'ticket.reply': 'Admin reply',
    'ticket.status': 'Status',
    'ticket.open': 'Open',
    'ticket.answered': 'Answered',
    'ticket.closed': 'Closed',
    'ticket.create_success': 'Ticket created!',
    'ticket.subject_required': 'Please enter subject',
    'ticket.message_required': 'Please enter message',
    
    // Notification
    'notif.title': '📢 Notifications',
    'notif.no_data': 'No notifications',
    'notif.new_order': 'New order',
    'notif.order_updated': 'Order updated',
    'notif.order_cancelled': 'Order cancelled',
    'notif.deposit_success': 'Deposit successful',
    'notif.deposit_failed': 'Deposit failed',
    'notif.account_locked': 'Account locked',
    'notif.account_unlocked': 'Account unlocked',
    'notif.password_reset': 'Password reset',
    'notif.broadcast': 'Broadcast from admin',
    
    // Admin
    'admin.title': '👑 KNOX Admin',
    'admin.dashboard': '📊 Dashboard',
    'admin.orders': '📦 Orders',
    'admin.deposits': '💳 Deposits',
    'admin.cards': '💳 Cards',
    'admin.tickets': '🎫 Tickets',
    'admin.users': '👥 Users',
    'admin.scripts': '📜 Scripts',
    'admin.deals': '🔥 Hot Deals',
    'admin.vouchers': '🎫 Vouchers',
    'admin.reviews': '⭐ Reviews',
    'admin.broadcast': '📢 Broadcast',
    'admin.logs': '📋 Logs',
    'admin.backup': '💾 Backup',
    'admin.logout': 'Logout',
    'admin.stat_orders': 'Total orders',
    'admin.stat_pending_orders': 'Pending orders',
    'admin.stat_completed_orders': 'Completed',
    'admin.stat_pending_deposits': 'Pending deposits',
    'admin.stat_pending_cards': 'Pending cards',
    'admin.stat_open_tickets': 'Open tickets',
    'admin.stat_users': 'Total users',
    'admin.stat_revenue': 'Revenue',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.reject_reason': 'Reject reason',
    'admin.reject_required': 'Please enter reject reason',
    'admin.backup_success': 'Backup successful!',
    'admin.broadcast_sent': 'Broadcast sent to all users!',
    
    // Products
    'products.mod_skill': 'Mod Skill',
    'products.mod_fish': 'Mod Fish',
    'products.mod_level': 'Mod Level',
    'products.mod_item': 'Mod Item',
    'products.mod_pet': 'Mod Pet',
    'products.mod_diamond': 'Mod Diamond',
    'products.mod_dieuhon': 'Mod Dieuhon',
    'products.mod_full': 'Full Package',
    'products.sniper_arena': 'Sniper Arena',
    'products.ban_mod': 'Custom Mod',
    'products.cau_chung': 'Hourly Fishing',
    
    // Hot Deals
    'hot_deals.title': '🔥 HOT DEALS',
    'hot_deals.no_data': 'No hot deals available',
    'hot_deals.discount': 'Off',
    
    // Dashboard
    'dashboard.title': '📊 Dashboard',
    'dashboard.balance': 'Balance',
    'dashboard.total_deposited': 'Total deposited',
    'dashboard.total_spent': 'Total spent',
    'dashboard.total_orders': 'Orders',
    'dashboard.completed_orders': 'Completed',
    'dashboard.vip_level': 'VIP',
    'dashboard.next_vip': 'Next VIP',
    'dashboard.need_more': 'Need more',
    'dashboard.current_discount': 'Current discount',
    'dashboard.reached_max': 'Reached VIP4',
    
    // Top Deposit
    'top_deposit.title': '🏆 Top depositors',
    'top_deposit.no_data': 'No deposit data',
    
    // Referral
    'referral.title': '👥 Refer friends',
    'referral.code': 'Referral code',
    'referral.reward': 'Referral reward: +10.000đ/person',
    'referral.count': 'Referred count',
    
    // Voucher
    'voucher.title': '🎫 Vouchers',
    'voucher.code': 'Code',
    'voucher.discount': 'Discount',
    'voucher.used': 'Used',
    'voucher.max_uses': 'Max uses',
    'voucher.apply_success': 'Applied successfully!',
    'voucher.invalid': 'Invalid code',
    'voucher.expired': 'Code expired',
    
    // Review
    'review.title': '⭐ Product review',
    'review.rating': 'Stars',
    'review.comment': 'Comment',
    'review.thank_you': 'Thank you for your review!',
    
    // Time
    'time.today': 'Today',
    'time.this_week': 'This week',
    'time.this_month': 'This month',
    'time.this_year': 'This year',
    
    // PWA
    'pwa.install': '📲 Install app',
    'pwa.install_desc': 'Install KNOX Shop to home screen for better experience!',
    'pwa.install_btn': 'Install',
    'pwa.install_later': 'Later',
    
    // Chat
    'chat.title': '📞 Contact',
    'chat.zalo': '💬 Zalo',
    'chat.telegram': '✈️ Telegram'
  }
};

// Hàm lấy text theo ngôn ngữ hiện tại
function getText(key, lang = 'vi') {
  const keys = key.split('.');
  let obj = LANG[lang];
  for (const k of keys) {
    if (obj && obj[k] !== undefined) {
      obj = obj[k];
    } else {
      return key;
    }
  }
  return obj || key;
      }
