const LANG = {
    vi: {
        home: "Trang Chủ",
        products: "Sản Phẩm",
        top_deposit: "Top Nạp",
        reviews: "Đánh Giá",
        login: "Đăng Nhập",
        register: "Đăng Ký",
        balance: "Số Dư",
        deposit: "Nạp Tiền",
        history: "Lịch Sử",
        dashboard: "Dashboard",
        logout: "Đăng Xuất",
        buy: "Mua Ngay",
        price: "Giá",
        contact: "Liên Hệ",
        game_account: "Tài khoản game",
        game_password: "Mật khẩu game",
        voucher: "Mã giảm giá",
        note: "Ghi chú",
        submit: "Xác Nhận",
        cancel: "Hủy",
        username: "Tên đăng nhập",
        password: "Mật khẩu",
        re_password: "Nhập lại mật khẩu",
        referral: "Mã giới thiệu (nếu có)",
        email: "Email (tùy chọn)",
        admin_panel: "Admin Panel"
    },
    en: {
        home: "Home",
        products: "Products",
        top_deposit: "Top Deposit",
        reviews: "Reviews",
        login: "Login",
        register: "Register",
        balance: "Balance",
        deposit: "Deposit",
        history: "History",
        dashboard: "Dashboard",
        logout: "Logout",
        buy: "Buy Now",
        price: "Price",
        contact: "Contact",
        game_account: "Game Account",
        game_password: "Game Password",
        voucher: "Voucher Code",
        note: "Note",
        submit: "Submit",
        cancel: "Cancel",
        username: "Username",
        password: "Password",
        re_password: "Confirm Password",
        referral: "Referral Code (optional)",
        email: "Email (optional)",
        admin_panel: "Admin Panel"
    }
};